# Generated by Django 3.2 on 2022-06-27 20:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20220628_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 27, 20, 41, 51, 237734, tzinfo=utc)),
        ),
    ]
